export * from './utente.model';
export * from './medico.model';
export * from './administrador.model';
export * from './prescricao.model';
export * from './exame.model';
export * from './avaliacao-carat.model';
export * from './alerta.model';
export * from './limiar-alerta.model';
export * from './auditoria.model';
